# Generated by Django 4.2.7 on 2025-06-29 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=200)),
                ('departure_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('departure_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('arrival_location', models.CharField(max_length=200)),
                ('arrival_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('arrival_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival_time', models.DateTimeField()),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_days', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='communities.community')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pickup_location', models.CharField(blank=True, max_length=200)),
                ('dropoff_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip')),
            ],
            options={
                'unique_together': {('trip', 'passenger')},
            },
        ),
    ]
